In [3]:
import numpy as np

In [13]:
arr=np.array([1,2,3,4,5])
print("after addition:", arr+2)
print("after multiplication:", arr*3)
print("after division:", arr/2)

after addition: [3 4 5 6 7]
after multiplication: [ 3  6  9 12 15]
after division: [0.5 1.  1.5 2.  2.5]


In [15]:
arr = np.array([1,2,3,6,4,5])
print(arr[::-1])

[5 4 6 3 2 1]


In [17]:
def most_frequent(array):
    unique, counts = np.unique(array, return_counts=True)  
    most_frequent_value = unique[np.argmax(counts)] 
    indices = np.where(array == most_frequent_value)[0]  
    return most_frequent_value, indices


x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1])
most_frequent_x, indices_x = most_frequent(x)
print("Most frequent value in x:", most_frequent_x)
print("Indices:", indices_x)


y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_frequent_y, indices_y = most_frequent(y)
print("Most frequent value in y:", most_frequent_y)
print("Indices:", indices_y)

Most frequent value in x: 1
Indices: [0 5 7 8]
Most frequent value in y: 1
Indices: [0 1 2]


In [19]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0,1])
print(arr[2,0])

20
70


In [21]:
Manika = np.linspace(10,100,25)
print("Dimensions:",Manika.ndim)
print("Shape:",Manika.shape)
print("Size:",Manika.size)
print("Data Type:",Manika.dtype)
print("Total Bytes:",Manika.nbytes)
transposed_array = Manika.reshape(5,5)
print("Using T attribute (Does not work for 1D array):",Manika.T)

Dimensions: 1
Shape: (25,)
Size: 25
Data Type: float64
Total Bytes: 200
Using T attribute (Does not work for 1D array): [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [23]:
ucs420_array = np.array([[10, 20, 30, 40], 
                         [50, 60, 70, 80], 
                         [90, 15, 20, 35]])
mean_value = np.mean(ucs420_array)
median_value = np.median(ucs420_array)
max_value = np.max(ucs420_array)
min_value = np.min(ucs420_array)
unique_elements = np.unique(ucs420_array)
reshaped_ucs420_Manika = ucs420_array.reshape(4, 3)
resized_ucs420_Manika = np.resize(ucs420_array, (2, 3))
print("Original 2D Array (3x4):\n", ucs420_array)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_elements)
print("\nReshaped Array (4x3):\n", reshaped_ucs420_Manika)
print("\nResized Array (2x3):\n", resized_ucs420_Manika)

Original 2D Array (3x4):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
